export const GET_CRICKET_MATCH_DATA_START = "GET_CRICKET_MATCH_DATA";
export const GET_CRICKET_MATCH_DATA_SUCCESS = "GET_CRICKET_MATCH_DATA_SUCCESS";
export const GET_CRICKET_MATCH_DATA_FAILED = "GET_CRICKET_MATCH_DATA_FAILED";
export const UPDATE_CRICKET_RECORD_START = "UPDATE_CRICKET_RECORD_START";
export const UPDATE_CRICKET_RECORD_SUCCESS = "UPDATE_CRICKET_RECORD_SUCCESS";
export const UPDATE_CRICKET_RECORD_FAILED = "UPDATE_CRICKET_RECORD_FAILED";
export const GET_FUNDBALANCE_START = "GET_FUNDBALANCE_START";
export const GET_FUNDBALANCE_SUCCESS = "GET_FUNDBALANCE_SUCCESS";
export const GET_FUNDBALANCE_FAILED = "GET_FUNDBALANCE_FAILED";

