export const Players = [

    {
        id: 1,
        name: "Minhaj Ahmad Khan",
        image: "Assets/Profile pics/Minhaj.svg",
        speciality: "All Rounder",
        instagram: "https://www.instagram.com/minhaj.mak/",
        facebook: "https://www.facebook.com/minhaj.a.khan.14",
        twitter: "https://twitter.com/MinhajAhmadKha7",
        phone: "8423544136",
        isActive:true,
        email: "minhaj.space@gmail.com",
        imageLink : "https://pbs.twimg.com/profile_images/1339577745819410432/CinNyORB_400x400.jpg"
        
    },
    {
        id: 2,
        name: "Zain Zaman Khan",
        image: "Assets/Profile pics/zain.svg",
        speciality: "Batsman",
        instagram: "https://www.instagram.com/zain.khan025/",
        facebook: "https://www.facebook.com/zainkhanbly",
        twitter: "#",
        phone: "8081953847",
        isActive:true,
        email: "suleman.khan@turtlelimited.com"
    },
    {
        id: 3,
        name: "Osama Hannan",
        image: "Assets/Profile pics/Osama.svg",
        speciality: "Batsman",
        instagram: "https://www.instagram.com/osamahannan5/",
        facebook: "https://www.facebook.com/profile.php?id=100010625177535",
        twitter: "https://twitter.com/Osamahannan1",
        phone: "8181007105",
        isActive:true,
        email: "osamahannan7@gmail.com",
        imageLink:"https://scontent.fknu1-2.fna.fbcdn.net/v/t1.6435-9/135059566_1280068079024019_6551271908970920219_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=e3f864&_nc_ohc=PpSnqBiOQAUAX_MN4Ub&_nc_ht=scontent.fknu1-2.fna&oh=00_AT89lYp-rLBGe4EYPCAdpW0f-LC7_LBvYV4GTAi57dxy7Q&oe=6289D502"
    },
    {
        id: 4,
        name: "Mohd Faiz",
        image: "Assets/Profile pics/Faiz.svg",
        speciality: "All Rounder",
        instagram: "https://www.instagram.com/mohd.faiz06/",
        facebook: "https://www.facebook.com/mdfaiz.06",
        twitter: "https://twitter.com/mohdfaiz714",
        phone: "9956536117",
        isActive:true,
        email: "faizxtylish@gmail.com",
        imageLink :"https://scontent-del1-1.xx.fbcdn.net/v/t1.6435-9/136667072_1819242251561921_4280174916959543301_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=OjsVzya8fPMAX8Bgf-h&tn=1yEVk4LqWja75sKO&_nc_ht=scontent-del1-1.xx&oh=00_AT_UcCviwdLNYIukd9RvGyMwN83p6lRqMF1rAFvPG6AHGg&oe=62868EBE"
    },
    {
        id: 5,
        name: "Asad Raiyan",
        image: "Assets/Profile pics/asad.svg",
        speciality: "Batsman",
        instagram: "#",
        facebook: "#",
        twitter: "#",
        phone: "8181079906",
        isActive:true,
        email: "dummyemail@gmail.com",
        imageLink:"https://scontent.fixr3-2.fna.fbcdn.net/v/t1.6435-9/128825862_1751949554960360_525978860648536276_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=nZ3tnbC8VZIAX9o2P2M&_nc_ht=scontent.fixr3-2.fna&oh=00_AT8DF9efAhmmYxGcFDp_6VP7u3LoxtWe_cHmsykvkX4dBg&oe=6286E7E3"
    },
    {
        id: 6,
        name: "Syed Faraz",
        image: "Assets/Profile pics/syed.svg",
        speciality: "All Rounder",
        instagram: "https://instagram.com/syedfaraz36?utm_medium=copy_link",
        facebook: "https://www.facebook.com/faraz.ahmad.73550",
        twitter: "#",
        phone: "9369912431",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 7,
        name: "Mohd Rashid",
        image: "Assets/Profile pics/rashid.svg",
        speciality: "All Rounder",
        instagram: "https://instagram.com/md.rashid7.86?utm_medium=copy_link",
        facebook: "https://www.facebook.com/sha.nu.3192",
        twitter: "#",
        phone: "9140444476",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 8,
        name: "Atif Shaikh",
        image: "Assets/Profile pics/atif.svg",
        speciality: "All Rounder",
        instagram: "https://instagram.com/atifshaikh32?utm_medium=copy_link",
        facebook: "https://www.facebook.com/profile.php?id=100009438409984",
        twitter: "#",
        phone: "8429398248",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 9,
        name: "Shahbaz Ahmad Khan",
        image: "Assets/Profile pics/shahbaz.svg",
        speciality: "All Rounder",
        instagram: "https://instagram.com/shahbazahmed.k?utm_medium=copy_link",
        facebook: "https://www.facebook.com/shahbazahmedkhan.sak.1",
        twitter: "#",
        phone: "7080337727",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 10,
        name: "Irfan Khan",
        image: "Assets/Profile pics/Irfan.svg",
        speciality: "All Rounder",
        instagram: "https://instagram.com/irfan_ik_pathan?utm_medium=copy_link",
        facebook: "https://www.facebook.com/profile.php?id=100012420880461",
        twitter: "#",
        phone: "9696255752",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 11,
        name: "Intzar Khan",
        image: "Assets/Profile pics/Intzar.svg",
        speciality: "Bowler",
        instagram: "https://instagram.com/intzarkhanstylash?utm_medium=copy_link",
        facebook: "https://www.facebook.com/profile.php?id=100005248029914",
        twitter: "https://twitter.com/KhanStylash?t=D7SRZFlngcFc7NU0oAUzjg&s=08",
        phone: "7348196441",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 12,
        name: "Sajid Khan",
        image: "Assets/Profile pics/sajid2.svg",
        speciality: "Batsman",
        instagram: "https://instagram.com/mr_sid7786?utm_medium=copy_link",
        facebook: "https://www.facebook.com/shaina.khatoon.1428",
        twitter: "#",
        phone: "7398069754",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 13,
        name: "Sameer Khan",
        image: "Assets/Profile pics/sameer.svg",
        speciality: "Batsman",
        instagram: "https://www.instagram.com/samtalib251/?utm_medium=copy_link",
        facebook: "https://www.facebook.com/people/Abu-Talib/100027192752298/",
        twitter: "https://twitter.com/Abutali55373948?t=gUzOWq_5cIXjlxrkXROWEQ&s=08",
        phone: "7985086452",
        isActive:false,
        email: "samtalib251@gmail.com"
    },
    {
        id: 14,
        name: "Shareef Gazi",
        image: "Assets/Profile pics/shareef.svg",
        speciality: "Batsman",
        instagram: "#",
        facebook: "#",
        twitter: "#",
        phone: "9795106463",
        isActive:false,
        email: "dummyemail@gmail.com"
    },
    {
        id: 15,
        name: "Tahir Ali",
        image: "Assets/Profile pics/tahir.svg",
        speciality: "Batsman",
        instagram: "#",
        facebook: "#",
        twitter: "#",
        phone: "+966595378927",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 14,
        name: "Idrees Ahmad",
        image: "Assets/Profile pics/idress.jpg",
        speciality: "Batsman",
        instagram: "#",
        facebook: "#",
        twitter: "#",
        phone: "9795106463",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
    {
        id: 14,
        name: "Ali",
        image: "Assets/Profile pics/dummy.png",
        speciality: "Batsman",
        instagram: "#",
        facebook: "#",
        twitter: "#",
        phone: "#",
        isActive:true,
        email: "dummyemail@gmail.com"
    },
     {
        id: 1,
        name: "Mohd Imran",
        image: "Assets/Profile pics/imran.svg",
        speciality: "All Rounder",
        instagram: "https://www.instagram.com/minhaj.mak/",
        facebook: "https://www.facebook.com/minhaj.a.khan.14",
        twitter: "https://twitter.com/MinhajAhmadKha7",
        phone: "8423544136",
        isActive:true,
        email: "minhaj.space@gmail.com",
        imageLink : "https://scontent.fknu1-4.fna.fbcdn.net/v/t39.30808-6/278347007_1430433754047307_1437913318459984063_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=tcEWyqaRy5MAX88G1Xm&_nc_ht=scontent.fknu1-4.fna&oh=00_AT_Cf0E4NXSGAJh26I8QqO4nXRUwG15MBvvpF_ebsFPx1w&oe=62677532"
        
    },


]